In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# 合并数据集
## 数据库风格的DataFrame合并

In [2]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})

In [3]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [4]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})

In [5]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [6]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [7]:
pd.merge(df1, df2, on = 'key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})

In [9]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})

In [10]:
pd.merge(df3, df4, left_on = 'lkey', right_on = 'rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [11]:
pd.merge(df1, df2, how = 'outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [12]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [13]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5)})

In [14]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [15]:
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [16]:
pd.merge(df1, df2, on = 'key', how = 'left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [17]:
pd.merge(df1, df2, how = 'inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [18]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                    'key2': ['one', 'two', 'three'],
                    'lval': [1,2,3]})

In [19]:
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                     'key2': ['one', 'one', 'one', 'two'],
                     'rval': [4,5,6,7]})

In [20]:
pd.merge(left, right, on = ['key1', 'key2'], how = 'outer')

key1   key2  lval  rval
0  foo    one   1.0   4.0
1  foo    one   1.0   5.0
2  foo    two   2.0   NaN
3  bar  three   3.0   NaN
4  bar    one   NaN   6.0
5  bar    two   NaN   7.0

In [21]:
pd.merge(left, right, on = 'key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar  three     3    one     6
5  bar  three     3    two     7

In [22]:
pd.merge(left, right, on = 'key1', suffixes = ('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar     three     3        one     6
5  bar     three     3        two     7

## 索引上的合并

In [23]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                    'value': range(6)})

In [24]:
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index = ['a', 'b'])

In [25]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [26]:
right1

group_val
a        3.5
b        7.0

In [27]:
pd.merge(left1, right1, left_on = 'key', right_index = True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [28]:
pd.merge(left1, right1, left_on = 'key', right_index = True, how = 'outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [29]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
                     'key2': [2000, 2001, 2002, 2001, 2002],
                     'data': np.arange(5.)})

In [30]:
righth = pd.DataFrame(np.arange(12).reshape((6,2)),
                     index = [['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                             [2001, 2000, 2000, 2000, 2001, 2002]],
                     columns = ['event1', 'event2'])

In [31]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [32]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [33]:
pd.merge(lefth, righth, left_on = ['key1', 'key2'], right_index = True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [34]:
pd.merge(lefth, righth, left_on = ['key1', 'key2'], right_index = True, how = 'outer')

data    key1  key2  event1  event2
0   0.0    Ohio  2000     4.0     5.0
0   0.0    Ohio  2000     6.0     7.0
1   1.0    Ohio  2001     8.0     9.0
2   2.0    Ohio  2002    10.0    11.0
3   3.0  Nevada  2001     0.0     1.0
4   4.0  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000     2.0     3.0

In [35]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]], 
                     index = ['a', 'c', 'e'], 
                     columns = ['Ohio', 'Nevada'])

In [36]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13., 14.]], 
                      index = ['b', 'c', 'd', 'e'], 
                      columns = ['Missouri', 'Alabama'])

In [37]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [38]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [39]:
pd.merge(left2, right2, how = 'outer', left_index = True, right_index = True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [40]:
left2.join(right2, how = 'outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [41]:
left1.join(right1, on = 'key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [42]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                      index = ['a', 'c', 'e', 'f'], columns = ['New York', 'Oregon'])

In [43]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [44]:
left2.join([right2, another], how = 'outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

## 轴向连接

In [45]:
arr = np.arange(12).reshape((3, 4))

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
np.concatenate([arr, arr], axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [48]:
s1 = pd.Series([0, 1], index = ['a', 'b'])

In [49]:
s2 = pd.Series([2, 3, 4], index = ['c', 'd', 'e'])

In [50]:
s3 = pd.Series([5, 6], index = ['f', 'g'])

In [51]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [52]:
pd.concat([s1, s2, s3], axis = 1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [53]:
s4 = pd.concat([s1 * 5, s3])

In [54]:
pd.concat([s1, s4], axis = 1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [55]:
pd.concat([s1, s4], axis = 1, join = 'inner')

0  1
a  0  0
b  1  5

In [58]:
pd.concat([s1, s4], axis = 1, join_axes = [['a', 'c', 'b', 'e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [59]:
result = pd.concat([s1, s1, s3], keys = ['one', 'two', 'three'])

In [60]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [61]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [62]:
pd.concat([s1, s2, s3], axis = 1, keys = ['one', 'two', 'three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [63]:
df1 = pd.DataFrame(np.arange(6).reshape((3,2)), index = ['a', 'b', 'c'], columns = ['one', 'two'])

In [64]:
df2 = pd.DataFrame(5 + np.arange(4).reshape((2,2)), index = ['a', 'c'], columns = ['three', 'four'])

In [65]:
pd.concat([df1, df2], axis = 1, keys = ['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [66]:
pd.concat({'level1': df1, 'level2': df2}, axis = 1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

pd.concat([df1, df2], axis = 1, keys = ['level1', 'level2'], names = ['upper', 'lower'])

In [68]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns = ['a', 'b', 'c', 'd'])

In [69]:
df2 = pd.DataFrame(np.random.randn(2, 3), columns = ['b', 'd', 'a'])

In [70]:
df1

a         b         c         d
0 -0.667392  0.410700 -2.227663  0.749243
1  1.852105 -0.012227  0.536322  0.049560
2 -0.401478 -0.378015  0.437160 -0.802362

In [71]:
df2

b         d         a
0  0.594735  0.644392 -1.004419
1 -0.008388 -1.661690  0.681226

In [72]:
pd.concat([df1, df2], ignore_index = True)

a         b         c         d
0 -0.667392  0.410700 -2.227663  0.749243
1  1.852105 -0.012227  0.536322  0.049560
2 -0.401478 -0.378015  0.437160 -0.802362
3 -1.004419  0.594735       NaN  0.644392
4  0.681226 -0.008388       NaN -1.661690

## 合并重叠数据

In [73]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan], index = ['f', 'e', 'd', 'c', 'b', 'a'])

In [74]:
b = pd.Series(np.arange(len(a), dtype = np.float64), index = ['f', 'e', 'd', 'c', 'b', 'a'])

In [75]:
b[-1] = np.nan

In [76]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [77]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [78]:
np.where(pd.isnull(a), b, a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [79]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [81]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                   'b': [np.nan, 2., np.nan, 6.],
                   'c': range(2, 18, 4)})

In [82]:
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                   'b': [np.nan, 3., 4., 6., 8.]})

In [83]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN