In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.27622303,  1.35670544, -0.85362137],
       [-0.98770306,  0.27305868,  1.06606821]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

# 创建ndarray

In [6]:
data1 = [6, 7.5, 8, 0, 1]

In [7]:
arr1 = np.array(data1)

In [8]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [9]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [16]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((3,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
np.empty((2,3,2))

array([[[  1.63099765e-316,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# ndarray的数据类型

In [20]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [21]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([1,2,3,4,5])

In [25]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr.dtype

dtype('float64')

In [28]:
arr = np.random.randn(4)

In [29]:
arr

array([-0.01750919, -1.99113171,  0.01726544, -0.05064676])

In [30]:
arr.astype(np.int32)

array([ 0, -1,  0,  0], dtype=int32)

In [31]:
numeric_strings = np.array(['1.25', '-9.6'], dtype = np.string_)

In [32]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 ])

In [33]:
int_array = np.arange(10)

In [34]:
calibers = np.array([0.22, 0.27], dtype = np.float64)

In [35]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [36]:
empty_uint32 = np.empty(8, dtype = 'u4')

In [37]:
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

# 数组和标量之间的运算

In [39]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [40]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [41]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [42]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [43]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

# 基本的索引和切片

In [44]:
arr = np.arange(10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [48]:
arr[5:8] = 12

In [49]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice = arr[5:8]

In [51]:
arr_slice[1] = 12345

In [52]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [54]:
arr_slice[:] = 64

In [55]:
arr_slice

array([64, 64, 64])

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[2]

array([7, 8, 9])

In [60]:
arr2d[0,2]

3

In [61]:
arr2d[0][2]

3

In [62]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10, 11, 12]]])

In [63]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
old_value = arr3d[0].copy()

In [66]:
arr3d[0] = 42

In [67]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
old_value

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3d[0] = old_value

In [70]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# 切片索引

In [72]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [73]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [77]:
arr2d[1, :2]

array([4, 5])

In [78]:
arr2d[2, :1]

array([7])

In [79]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [80]:
arr2d[:2, 1:] = 0

In [82]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# 布尔型索引

In [83]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [84]:
data = np.random.randn(7,4)

In [85]:
data

array([[ 0.49188471, -0.4662333 , -0.79092367, -0.05989926],
       [ 1.37950751, -2.05622345, -0.85738359, -0.51587706],
       [-0.59023252,  0.67922294,  0.82356097,  0.2467357 ],
       [ 2.56838444, -0.28842757,  2.00786501,  0.10013941],
       [-1.93995751,  2.08472714, -0.39344476, -0.04348294],
       [-0.01442581,  0.72751101, -0.54491596, -0.83314305],
       [-0.25955005,  1.07602597,  1.69575242, -0.14558277]])

In [86]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [87]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [88]:
data[names == 'Bob']

array([[ 0.49188471, -0.4662333 , -0.79092367, -0.05989926],
       [ 2.56838444, -0.28842757,  2.00786501,  0.10013941]])

In [89]:
data[names == 'Bob', 2:]

array([[-0.79092367, -0.05989926],
       [ 2.00786501,  0.10013941]])

In [90]:
data[names == 'Bob', 3]

array([-0.05989926,  0.10013941])

In [91]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [92]:
data[-(names == 'Bob')]

/home/yi/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 1.37950751, -2.05622345, -0.85738359, -0.51587706],
       [-0.59023252,  0.67922294,  0.82356097,  0.2467357 ],
       [-1.93995751,  2.08472714, -0.39344476, -0.04348294],
       [-0.01442581,  0.72751101, -0.54491596, -0.83314305],
       [-0.25955005,  1.07602597,  1.69575242, -0.14558277]])

In [93]:
mask = (names == 'Bob') | (names == 'Will')

In [94]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [95]:
data[mask]

array([[ 0.49188471, -0.4662333 , -0.79092367, -0.05989926],
       [-0.59023252,  0.67922294,  0.82356097,  0.2467357 ],
       [ 2.56838444, -0.28842757,  2.00786501,  0.10013941],
       [-1.93995751,  2.08472714, -0.39344476, -0.04348294]])

In [96]:
data[data < 0 ] = 0

In [97]:
data

array([[ 0.49188471,  0.        ,  0.        ,  0.        ],
       [ 1.37950751,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.67922294,  0.82356097,  0.2467357 ],
       [ 2.56838444,  0.        ,  2.00786501,  0.10013941],
       [ 0.        ,  2.08472714,  0.        ,  0.        ],
       [ 0.        ,  0.72751101,  0.        ,  0.        ],
       [ 0.        ,  1.07602597,  1.69575242,  0.        ]])

In [98]:
data[names != 'Joe'] = 7

In [99]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.37950751,  0.        ,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.72751101,  0.        ,  0.        ],
       [ 0.        ,  1.07602597,  1.69575242,  0.        ]])

# 花式索引

In [100]:
arr = np.empty((8,4))

In [101]:
for i in range(8):
    arr[i] = i

In [102]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [103]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [104]:
arr[[-3, -5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [105]:
arr = np.arange(32).reshape((8,4))

In [106]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
arr[[1,5,7,3], [0,3,1,2]]

array([ 4, 23, 29, 14])

In [109]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [110]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# 数组转置和轴对换

In [111]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [113]:
arr = np.random.randn(6,3)

In [114]:
np.dot(arr.T, arr)

array([[ 6.06187676,  4.72646331, -1.73675651],
       [ 4.72646331,  7.54317626, -2.36887948],
       [-1.73675651, -2.36887948,  9.18951068]])

In [115]:
arr = np.arange(16).reshape((2,2,4))

In [116]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [117]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [118]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [119]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])