# **Pickle**

In [1]:
import numpy as np
from random import gauss
a = [gauss(1.5, 2.0) for i in xrange(10000)]

In [2]:
a

[-1.1314024236229137,
 2.9738050710910278,
 1.0806003664947559,
 0.635227433993479,
 3.36826437735614,
 -0.3195377066743885,
 2.6108519540996973,
 2.6559858220120636,
 2.4764972868128767,
 0.3219511928261598,
 -0.018807116541945224,
 1.3349666286128778,
 4.337535368661843,
 -1.1707724910781825,
 -0.4759001938165728,
 -1.0350135562148055,
 1.094103262174622,
 0.2542351028454892,
 1.5667200090066526,
 0.4566826804739397,
 -1.7111612521604402,
 -0.18771023513777463,
 0.6213744925861313,
 3.274150111362338,
 -0.18959054243883244,
 1.8798023549167442,
 -0.3262068036251522,
 -1.0471232576665308,
 0.8500234457633222,
 1.5159367383419429,
 1.3261480508714263,
 4.023601895797675,
 2.7000150383495356,
 3.3913987353426736,
 -0.7768287972820418,
 0.12136331859512262,
 -1.4017805570932023,
 4.158679990737074,
 0.5767328656077617,
 4.539811204192335,
 1.8813075294486368,
 0.611212249452197,
 2.818052644053099,
 3.8309498090805336,
 1.0750419369549227,
 0.6474259527022503,
 -0.9222088716554224,
 5.76

In [3]:
import pickle
pkl_file = open('data.pkl', 'w')

In [4]:
%time pickle.dump(a, pkl_file)

CPU times: user 40 ms, sys: 4 ms, total: 44 ms
Wall time: 65.9 ms


In [5]:
pkl_file.close()

In [6]:
pkl_file = open('data.pkl', 'r')

In [7]:
%time b = pickle.load(pkl_file)

CPU times: user 36 ms, sys: 0 ns, total: 36 ms
Wall time: 37.3 ms


In [8]:
b == a

True

In [9]:
np.allclose(np.array(a), np.array(b))

True

In [10]:
pkl_file.close()

** Use numpy ndarray would be faster**

In [11]:
pkl_file = open('data.pkl', 'w')
%time pickle.dump(np.array(a), pkl_file)
%time pickle.dump(np.array(a) ** 2, pkl_file)

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 16.1 ms
CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 10.8 ms


In [12]:
pkl_file.close()

In [13]:
pkl_file = open('data.pkl', 'r')

**One Item a time, FIFO**

In [14]:
x = pickle.load(pkl_file)
y = pickle.load(pkl_file)

In [15]:
x

array([-1.13140242,  2.97380507,  1.08060037, ...,  0.96033723,
       -1.09946295, -0.32343662])

In [16]:
y

array([ 1.28007144,  8.8435166 ,  1.16769715, ...,  0.92224759,
        1.20881879,  0.10461125])

In [17]:
pkl_file.close()

** put in a dictionary to give user more information**

In [18]:
pkl_file = open('data.pkl', 'w')
pickle.dump({'x': x, 'y': y}, pkl_file)
pkl_file.close()

In [19]:
pkl_file = open('data.pkl', 'r')
data = pickle.load(pkl_file)
pkl_file.close()
for d in data.keys():
    print d
    print data[d][:5]

y
[  1.28007144   8.8435166    1.16769715   0.40351389  11.34520492]
x
[-1.13140242  2.97380507  1.08060037  0.63522743  3.36826438]


# ** CSV File Read and Write ** #

In [20]:
rows = 5000
a = np.random.standard_normal((rows, 5)).round(4)

In [21]:
a

array([[ 1.2243, -0.4845, -0.9673, -0.8465, -1.4278],
       [ 0.5261, -0.4369, -0.5753, -0.1668,  1.3031],
       [-0.1199,  0.6264, -1.0836,  0.3416, -0.1222],
       ..., 
       [ 0.0273,  1.015 , -0.592 ,  0.0241, -0.7167],
       [-2.3443,  1.0667, -0.9786,  0.3928, -0.3401],
       [-1.0812,  0.8136, -0.2968, -0.4336,  0.9417]])

In [22]:
import pandas as pd

In [23]:
t = pd.date_range(start = '2014/1/1', periods = rows, freq = 'H')

In [24]:
csv_file = open('data.csv', 'w')

In [25]:
header = 'date, no1, no2, no3, no4, no5\n'
csv_file.write(header)

In [26]:
for tt, (no1, no2, no3, no4, no5) in zip(t, a):
    csv_file.write('%s,%f,%f,%f,%f,%f\n' % (tt, no1, no2, no3, no4, no5))

** Read one line per iteration **

In [27]:
csv_file.close()

In [28]:
csv_file = open('data.csv', 'r')

In [29]:
for i in range(5):
    print csv_file.readline(),

date, no1, no2, no3, no4, no5
2014-01-01 00:00:00,1.224300,-0.484500,-0.967300,-0.846500,-1.427800
2014-01-01 01:00:00,0.526100,-0.436900,-0.575300,-0.166800,1.303100
2014-01-01 02:00:00,-0.119900,0.626400,-1.083600,0.341600,-0.122200
2014-01-01 03:00:00,0.656400,-1.225100,-1.437100,-0.068600,0.732000


In [30]:
content = csv_file.readlines()

In [31]:
for line in content[:5]:
    print line

2014-01-01 04:00:00,0.069200,-0.434600,-1.109700,0.204500,0.714300

2014-01-01 05:00:00,-0.372100,0.452700,0.552900,0.855300,0.571000

2014-01-01 06:00:00,0.152200,-1.380700,-0.489000,0.888000,0.811100

2014-01-01 07:00:00,-0.328700,0.424500,-0.042800,0.092400,-1.266000

2014-01-01 08:00:00,0.495800,-0.854600,2.155200,-0.167400,0.723000



In [32]:
csv_file.close()

# ** SQLite ** #

In [33]:
import sqlite3 as sq3

In [34]:
query = 'CREATE TABLE numbs (Date date, No1 real, No2 real)'

In [35]:
con = sq3.connect('numbs.db')

In [36]:
con.execute(query)

OperationalError: table numbs already exists

In [ ]:
con.commit()

In [ ]:
import datetime as dt

In [ ]:
con.execute('INSERT INTO numbs VALUES(?, ?, ?)', (dt.datetime.now(), 0.12, 7.3))
con.commit()

In [ ]:
data = np.random.standard_normal((10000, 2)).round(5)

In [ ]:
for row in data:
    con.execute('INSERT INTO numbs VALUES(?, ?, ?)', (dt.datetime.now(), row[0], row[1]))
con.commit()

In [ ]:
con.execute('SELECT * FROM numbs').fetchmany(10)

In [ ]:
pointer = con.execute('SELECT * FROM numbs')
for i in range(3):
    print pointer.fetchone()

# **Read and Write Numpy array** #

In [ ]:
dtimes = np.arange('2015-01-01 10:00:00', '2021-12-31 22:00:00', dtype = 'datetime64[m]')

In [ ]:
dty = np.dtype([('Date', 'datetime64[m]'), ('No1', 'f'), ('No2', 'f')])
data = np.zeros(len(dtimes), dtype = dty)

In [ ]:
data['Date'] = dtimes

In [ ]:
a = np.random.standard_normal((len(dtimes), 2)).round(5)
data['No1'] = a[:, 0]
data['No2'] = a[:, 1]

In [ ]:
%time np.save('array', data)

In [ ]:
%time np.load('array.npy')

## **Pandas I/O** ##

In [ ]:
data = np.random.standard_normal((1000,5)).round(5)

In [ ]:
query = 'CREATE TABLE numbers (No1 real, No2 real, No3 real, No4 real, No5 real)'
con.close()

In [ ]:
con = sq3.Connection('numbss.db')

In [ ]:
con.execute(query)

In [ ]:
%%time 
con.executemany('INSERT INTO numbers VALUES (?, ?, ?, ?, ?)', data)
con.commit()

In [ ]:
%%time
temp = con.execute('SELECT * FROM numbers').fetchall()
print temp[0:2]
temp = 0.0

In [ ]:
%%time
query = 'SELECT * FROM numbers WHERE No1 > 0 AND No2 < 0'
res = np.array(con.execute(query).fetchall()).round(3)

In [ ]:
res = res[::100]

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(res[:, 0], res[:, 1], 'ro')
plt.grid(True)
plt.xlim(-0.5, 4.5)
plt.ylim(-4.5, 0.5)

In [ ]:
import pandas.io.sql as pds

In [ ]:
%time data = pds.read_sql('SELECT * FROM numbers', con)

In [ ]:
%time data[(data['No1'] > 0) & (data['No2'] < 0)]

In [ ]:
%%time
res = data[['No1', 'No2']][((data['No1'] > 0.5) | (data['No1'] < -0.5)) & ((data['No2'] < -1) | (data['No2'] > 1))]

In [ ]:
plt.plot(res.No1, res.No2, 'ro')
plt.grid(True)
plt.axis('tight')

In [ ]:
h5s = pd.HDFStore('data.h5s','w')
%time h5s['data'] = data

In [ ]:
h5s.close()

In [ ]:
%%time
h5s = pd.HDFStore('data.h5s', 'r')
temp = h5s['data']
h5s.close()

In [ ]:
np.allclose(np.array(temp), np.array(data))

** Pandas and CSV **

In [ ]:
%time data.to_csv('panda_data.csv')

In [ ]:
%%time
pd.read_csv('panda_data.csv')[['No1', 'No2', 'No3', 'No4']].hist(bins = 20)

** EXCEL **

In [ ]:
%time data.to_excel('pd_data.xlsx')

In [ ]:
%time pd.read_excel('pd_data.xlsx', 'Sheet1').cumsum().plot()

# **PyTables** #

In [ ]:
import tables as tb

In [ ]:
h5 = tb.open_file('tab.h5', 'w')

In [ ]:
rows = 200000

In [ ]:
row_des = {'Date': tb.StringCol(26, pos = 1),'No1': tb.IntCol(pos = 2),'No2': tb.IntCol(pos = 3),
           'No3': tb.IntCol(pos = 4),'No4': tb.IntCol(pos = 5)}

In [ ]:
filters = tb.Filters(complevel = 0)
tab = h5.create_table('/', 'ints_floats', row_des,
                     title = 'Integer and Float', expectedrows = rows, filters = filters)

In [ ]:
tab

In [ ]:
pointer = tab.row

In [ ]:
ran_int = np.random.randint(0, 10000, size = (rows, 2))
ran_flo = np.random.standard_normal((rows, 2)).round(5)

In [ ]:
%%time
for i in range(rows):
    pointer['Date'] = dt.datetime.now()
    pointer['No1'] = ran_int[i, 0]
    pointer['No2'] = ran_int[i, 1]
    pointer['No3'] = ran_flo[i, 0]
    pointer['No4'] = ran_flo[i, 1]
    pointer.append()

In [ ]:
tab.flush()

In [ ]:
tab

In [ ]:
dty = np.dtype([('Date', 'S26'), ('No1', '<i4'), ('No2', '<i4'), ('No3', '<f8'), ('No4', '<f8')])

In [ ]:
sarray = np.zeros(len(ran_int), dtype = dty)

In [ ]:
sarray

In [ ]:
%%time
sarray['Date'] = dt.datetime.now()
sarray['No1'] = ran_int[:, 0]
sarray['No2'] = ran_int[:, 1]
sarray['No3'] = ran_flo[:, 0]
sarray['No4'] = ran_flo[:, 1]

In [ ]:
%%time
h5.create_table('/', 'int_float_from_array', sarray,
               title = 'Integer and Float', expectedrows = rows, filters = filters)

In [ ]:
h5.remove_node('/', 'int_float_from_array')

In [ ]:
tab[:3]

In [ ]:
tab[:4]['No4']

In [ ]:
%time np.sum(tab[:]['No4'])

In [ ]:
%%time
plt.hist(tab[:]['No3'], bins = 30)
plt.grid(True)

In [ ]:
%%time
res = np.array([(row['No3'], row['No4']) for row in tab.where('((No3 < -0.5) | (No3 > 0.5)) & \
                                                              ((No4 < -1) | (No4 > 1))')])

In [ ]:
plt.plot(res.T[0], res.T[1], 'ro')
plt.grid(True)

**Compression**

In [ ]:
h5c = tb.open_file('tab.h5c', 'w')
filters = tb.Filters(complevel = 4, complib = 'blosc')
tabc = h5c.create_table('/', 'int_float', sarray, title = 'Integer and Float', expectedrows = rows, filters = filters)

In [ ]:
%%time
res = np.array([(row['No3'], row['No4']) for row in tabc.where('((No3 < -0.5) | (No3 > 0.5)) & \
                                                              ((No4 < -1) | (No4 > 1))')])

In [ ]:
%time dd = tab.read()
%time ddd = tabc.read()

** Array **

In [ ]:
%%time
arr_int = h5.create_array('/', 'integers', ran_int)
arr_flo = h5.create_array('/', 'floats', ran_flo)

In [ ]:
h5

** Calculation in harddisk **

In [ ]:
h5 = tb.open_file('array.h5', 'w')

In [ ]:
n = 1000
ear = h5.createEArray(h5.root, 'ear', atom = tb.Float64Atom(), shape = (0, n))

In [ ]:
%%time
rand = np.random.standard_normal((n,n))
for i in range(750):
    ear.append(rand)
ear.flush()

In [ ]:
ear

In [ ]:
ear.size_on_disk

In [ ]:
out = h5.createEArray(h5.root, 'out', atom = tb.Float64Atom(), shape = (0, n))

In [ ]:
#expr = tb.Expr('3 * sin(ear) + sqrt(abs(ear))')
#expr.setOutput(out, append_mode = True)